# ------------------ Deployment ------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-api
  template:
    metadata:
      labels:
        app: iot-sensor-api
    spec:
      containers:
        - name: iot-sensor-api
          image: iot-sensor-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---
# ------------------ LoadBalancer Service ------------------
apiVersion: v1
kind: Service
metadata:
  name: iot-sensor-service
spec:
  selector:
    app: iot-sensor-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
# ------------------ NodePort Service ------------------
apiVersion: v1
kind: Service
metadata:
  name: iot-sensor-api
spec:
  type: NodePort
  selector:
    app: iot-sensor-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000

---
# ------------------ Horizontal Pod Autoscaler ------------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iot-sensor-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-sensor-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
